<!DOCTYPE html>
<html lang="de">
<head>
   <meta charset="UTF-8"> 
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="css/style.css">
   <title>Veranstaltungskalender</title>
</head>
<body>
   
    <!-- Wrapper Bereich -->
    <div class="wrapper">

     <!-- Header Bereich -->
        <header>
            <h1>Veranstaltungskalender</h1>
            <nav>
                <ul>
                    <li> <a href="events.php">Home</a></li>
                    <li><a href="admin.php">Admin</a></li>

                </ul>
            </nav>

        </header>